spring:
  application:
    name: Spring
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: tad
    password: tad
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers=true:


server:
  port: 7777
